# Generated by Django 3.0.8 on 2020-07-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200719_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbTwo',
            field=models.ImageField(blank=True, default='defaults.gif', upload_to=''),
        ),
    ]
