# Generated by Django 3.0.8 on 2020-07-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_thumbtwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbTwo',
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.gif', upload_to=''),
        ),
    ]
