# Generated by Django 3.0.8 on 2020-07-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200719_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumb',
            new_name='thumb3',
        ),
    ]
