# Generated by Django 3.0.8 on 2020-07-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200719_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb3',
        ),
    ]
