# Generated by Django 3.0.8 on 2020-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_thumb3'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.gif', upload_to=''),
        ),
    ]
